name: Pull request to Org Main

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # 1. 
      - uses: actions/checkout@v2

      # 2. 
      - name: Start of pull request workflow
        run: echo "Start of pull request workflow"

      # 3.
      - name: Validate Packer Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ami.json
        env:
          PACKER_LOG: 1

      # 4.
      - name: End of pull request workflow
        run: echo "End of pull request workflow" 

