name: Before Merge to Main branch

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-ami:
    runs-on: ubuntu-latest

    steps:

      # 1. 
      - name: Start
        run: echo "Start" 

      # 2. 
      - uses: actions/checkout@v2

      # 3.
      - name: Validate Packer Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only 
          target: ami.json
        env:
          PACKER_LOG: 1 

      # 4. 
      - name: Generate AMI      
        run: |
          packer build \
            -var 'aws_access_key=${{ secrets.AWS_ACCESS_KEY }}' \
            -var 'aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}' \
            -var 'aws_region=${{ secrets.AWS_REGION }}' \
            -var 'subnet_id=${{ secrets.SUBNET_ID }}' \
            -var 'source_ami=${{ secrets.SOURCE_AMI }}' \
            -var 'ami_users=${{ secrets.PROD_ACCOUNT_NUMBER }}' \
            -color=false ami.json 

      # 5. 
      - name: The End
        run: echo "The End" 

